[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[project]
name = "buckyos"
version = "0.1.0"
dependencies = [
    "localStoragePy",
    "requests"
]
